//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineGamersPlatform.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int id { get; set; }
        public string gameType { get; set; }
        public string gameName { get; set; }
        public string gameNew { get; set; }
        public string gameNew2 { get; set; }
        public string gameNew3 { get; set; }
    }
}
